### ISSUE TITLE
Window is not borderless

### ISSUE THREAD

**Issue by SCOTT0852** [DeeChael/Concentration#1]
The game window is not actually made borderless. A full window screenshot will still capture the title bar + window borders, and the bottom two rounded corners are visible at the corners of the screen. One pixel of the borders will also be visible on an adjacent display.

The bottom left corner of my monitor, where you can see one corner of the game window.
![image](https://github.com/DeeChael/Concentration/assets/33875157/d7b80c67-1031-47bc-8a27-b0b6de41af9f)
A windowed screenshot taken with Snipping Tool. This is larger than my 1920x1200 monitors so it does not save to Windows clipboard history and I still need to manually crop out the borders. Note the single pixel line of pure white on the bottom as well as the left adjacent monitor (I don't have a monitor to the right of this one so the right border is not captured).
![image](https://github.com/DeeChael/Concentration/assets/33875157/64a0a3bc-0d47-4751-8c06-5a8ad0adc7d2)

For reference, a game that runs in a proper borderless mode will not have these issues (not fullscreened here because then it would just look like standard exclusive fullscreen):
![image](https://github.com/DeeChael/Concentration/assets/33875157/0b42dfb5-ad31-44d0-b1f4-f536f942b7f6)

Tested on Windows 11 with Concentration 1.0.3's Fabric release on Quilt, but I'm sure the issue applies to Windows 10 and other mod loaders as well. I really love how this mod works besides this one annoyance, so I'd like to see it live up to what it sets out to do.

**Comment by DeeChael** [comment]
I tested on my pc under 3 mod loaders but I can't reproduce what you showed, try toggle to windowed mode then toggle it back?

This is a weird problem and I'll keep this open until I find the solution.

Thanks for your report!

**Comment by DeeChael** [comment]
I tried to make the window not "decorated", but the fullscreen mode appears to be native mode instead of borderless, it's wired and I'm finding a way to fixed it.

**Comment by DeeChael** [comment]
There is also something I want to mention is: as the title bar is actuelly moved out of the monitor (Now I realised that if somebody connect the monitors vertically will see the title bar, so I must find a way to fix it as fast as I can), the snipping tool provided by Microsoft actuelly won't capture the title bar in my test:
![image](https://github.com/DeeChael/Concentration/assets/63186003/78a567c6-6e55-48da-84b8-2371fe53d8b0)

**Comment by DeeChael** [comment]
Okay I fixed this in a dirty way, maybe I will find a better way to solve this problem, but for now, this dirty way is surely enough

**Comment by shny-scott** [comment]
> the snipping tool provided by Microsoft actuelly won't capture the title bar in my test:

I believe it only captures anything in a rectangle that fits all your monitors, I have one horizontal monitor and one vertical monitor so a windowed screenshot can go above the horizontal one.
