### ISSUE TITLE
[Suggestion] Move fullscreen options to a new Group

### ISSUE THREAD

**Issue by DeeChael** [DeeChael/Concentration#11]
![image](https://github.com/DeeChael/Concentration/assets/63186003/5bbd9a7f-4dd7-4520-b5cb-f5997abefc38)
with Sodium Extras installed, there is a Fullscreen Resolution option.
I'm considering whether should I move Fullscreen and Mode option under the same group with Fullscreen Resolution
Leave your comments plz

**Comment by crg-mad** [comment]
yeah this would be nice i believe
