### ISSUE TITLE
backport to 1.20.4 possibly?

### ISSUE THREAD

**Issue by crg-mad** [DeeChael/Concentration#14]
as it is in the title

**Comment by DeeChael** [comment]
As other mods like [Cubes Without Borders](https://modrinth.com/mod/cubes-without-borders) exist, I think Concentration isn't necessary for lower version though that mod doesn't work on my pc. Another reason is the version naming is already mess up

**Comment by DeeChael** [comment]
Okay, actually I can backport for NeoForge platforms in the future, as Cubes Without Borders updated, I won't update Fabric version anymore.

I'll put a list here to list all the versions I will backport:

- [x] NeoForge 1.20.6 (Updated with the latest code in 1,21)
- [ ] NeoForge 1.20.5
- [ ] NeoForge 1.20.4
- [ ] NeoForge 1.20.3
- [ ] NeoForge 1.20.2
- [x] Forge&NeoForge 1.20.1
- [ ] Forge1.20

Plz close this issue after I published all the backports

**Comment by DeeChael** [comment]
1.20.6 backport finished, but not publish to modrinth yet

**Comment by DeeChael** [comment]
1.20.6 & 1.20.1 finished and published to modrinth

**Comment by DeeChael** [comment]
porting list moved to #36
