### ISSUE TITLE
Framerate drops when GUI is open in "fullscreen"

### ISSUE THREAD

**Issue by JasonHorkles** [DeeChael/Concentration#15]
When in the borderless fullscreen mode and a GUI is open (e.g. inventory, escape menu, etc), the framerate seems to tank in 1.21. This is easiest to reproduce with shaders enabled. The only enabled mods are Concentration 1.1.3, Fabric API, Indium, Iris, Lithium, and Sodium. Oddly enough, the issue goes away when trying to record it with OBS.

**Comment by DeeChael** [comment]
weird issue, checking

**Comment by DeeChael** [comment]
weird...
tested on my pc and it drops about 10 fps with shaders. maybe it's a problem related to windowed mode as borderless fullscreen actuall is just a window but fill your whole monitor.

i have no idea how to fix it, sorry

**Comment by JasonHorkles** [comment]
No worries, thanks anyways!

**Comment by JasonHorkles** [comment]
I seem to have made it happen without the mod as well in windowed mode so I wonder if something else is causing it instead
