### ISSUE TITLE
1.1.4 It seems like something was messed up...

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DeeChael/Concentration#20]
After entering the game using 1.1.4, what comes into view is not the main menu, but the error interface.

Log *(Deleted)*

**Comment by DeeChael** [comment]
should be fixed in 1.1.5

**Comment by 3gf8jv4dv** [comment]
Sorry, but the game crashes again in 1.1.5 when entering video settings or full screen. :(

Log1 *(Deleted)*, Log2 *(Deleted)*

**Comment by DeeChael** [comment]
I figured out the problem, neoforge team removed a method so i cant load the config by myself, but it doesn;t matter.
it should be fixed in 1.1.6, i promise
