### ISSUE TITLE
Borderless Fullscreen 1 pixel larger than the display's vertical size

### ISSUE THREAD

**Issue by JohnGoten** [DeeChael/Concentration#25]
https://mclo.gs/RRtFQ9w
![2024-09-18_21 05 48](https://github.com/user-attachments/assets/a4644058-a7f2-4ff0-a721-ce139505f392)
nit-picky for sure yet still important to mention as the user's expected behavior would be to retain the normal fullscreen resolution, e.g. 2560 x 1440 not 2560 x 144**1**

**Comment by DeeChael** [comment]
check #1
as i said
this ia a dirty way to fix minecraft not borderless problem
