### ISSUE TITLE
Version 2.0.0 Fabric not compatible with MC 1.21.1

### ISSUE THREAD

**Issue by LucidUnrest** [DeeChael/Concentration#28]
<html>Mod 'Concentration' (concentration) 2.0.0 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version<br>is present: 1.21.1!</html>

**Comment by NoltoxGit** [comment]
@DeeChael Yes, can you fix this bug please?

**Comment by DeeChael** [comment]
Fixed in 2.0.1
