### ISSUE TITLE
Does not work with Wayland

### ISSUE THREAD

**Issue by Enderteck** [DeeChael/Concentration#29]
This mod doesn't work when running minecraft on Wayland (natively) as the taskbar er the top bar isn't covered on the Gnome desktop.

Here's a screenshot:
![image](https://github.com/user-attachments/assets/1c5c7fa1-970a-4453-b751-df4bc588d445)
It is currently running as windowed but with no window decorations, it's not taking the full screen space, unlike every other implementation of berderless windowed I've seen.

Playing on Fedora 40
Minecraft 1.21.1
Fabric 16.5
Sodium v0.6.0beta
Running wiht Wayfix, but does't work with any kind of Wayland support.

**Comment by DeeChael** [comment]
ughhhhhhhh, it will take some time to fix it as i dont have any machine installed a linux distro with de on wayland

**Comment by DeeChael** [comment]
i dont know if i actually fixed it.
in 2.1.0 i replaced my dirty solution to fix the fullscreen problem with real borderless fullscreen, now im compiling it, try the new release 2.1.0 on modrinth later and tell me the result plz
@Enderteck

**Comment by Enderteck** [comment]
It looks like it mkes my game crashes with the new update...

Here is the crash report:

https://mclo.gs/JMO6WTR

Here's latest log:

https://mclo.gs/ek7wy3k

**Comment by DeeChael** [comment]
try 2.2.1? and try the Exclusive mode

**Comment by Enderteck** [comment]
Yes ! it works now ! Thank you, you saved my modpacks
