### ISSUE TITLE
crash: Ubuntu 24.02, MC 1.21.1 - Crashes when fullscreening (Required function is missing: glfwGetWin32Adapter)

### ISSUE THREAD

**Issue by StupidRepo** [DeeChael/Concentration#33]
# Logs
https://mclo.gs/zod67vU#L330
# Description
Crashes when going into fullscreen on Ubuntu 24.02.

* **Launcher**: Prism Launcher
* **Launcher installed from**: Flatpak/Flathub
* **MC**: 1.21.1
* **Platform**: Fabric

**Comment by DeeChael** [comment]
i forget to check if the platform is windows, sorry for that, i will fixed it in 2.2.0, ill release it after about 1 hour

**Comment by DeeChael** [comment]
Try 2.2.0, it fixed that this mod didn't check the system environment

**Comment by StupidRepo** [comment]
> Try 2.2.0, it fixed that this mod didn't check the system environment

Thank you! Will do this in a sec, I'm just installing a mod so it's good timing I see this right now. I figured this was what was happening lol.

**Comment by StupidRepo** [comment]
It works! But, it seems to crash when opening the video/graphics settings with Sodium enabled.

Here's that log:
https://mclo.gs/ZGtlLac

**Comment by DeeChael** [comment]
> It works! But, it seems to crash when opening the video/graphics settings with Sodium enabled.
> 
> Here's that log: https://mclo.gs/ZGtlLac

as i added a new fullscreen mode but forget to add new option to sodium's options, it crashed, ill fixed asap

**Comment by DeeChael** [comment]
try 2.2.1?

**Comment by StupidRepo** [comment]
> try 2.2.1?

Will do this in a sec :)

**Comment by StupidRepo** [comment]
Thank you! Works perfectly and no crashes :)
