### ISSUE TITLE
Crash when opening graphics settings in Sodium

### ISSUE THREAD

**Issue by zed1ker** [DeeChael/Concentration#34]
Logs: https://mclo.gs/UU27Req
2.2.0 mod version
0.6.0 sodium

**Comment by DeeChael** [comment]
as i added a new fullscreen mode but forget to add new option to sodium's options, it crashed, ill fixed asap

**Comment by DeeChael** [comment]
try 2.2.1?

**Comment by zed1ker** [comment]
it all works
