### ISSUE TITLE
CurseForge

### ISSUE THREAD

**Issue by Madis0** [DeeChael/Concentration#35]
Please consider publishing your mod to CurseForge for added exposure and to allow modpacks to include this more easily :)

**Comment by DeeChael** [comment]
okay, but only the latest version, is it ok?

**Comment by Madis0** [comment]
Sure, that's fine.

**Comment by DeeChael** [comment]
Published. https://www.curseforge.com/minecraft/mc-mods/concentration
but there is a little bug suddenly appeared (#37 ) and i dont have any idea how to fix it. it may have some impact on user's experience.

**Comment by Madis0** [comment]
Could you also consider enabling this? That would allow non-CF launchers to smoothly download it (e.g. Prism and GDLauncher)

![pilt](https://github.com/user-attachments/assets/06d5b2de-6bd2-4e82-9cfc-2ed569b8ad02)

**Comment by DeeChael** [comment]
done
