### ISSUE TITLE
Unable to un-fullscreen

### ISSUE THREAD

**Issue by Tatertot5s** [DeeChael/Concentration#38]
Environment: Windows 11, Prism Launcher
Mod Version: 2.2.4

Problem: When trying to un-fullscreen, it doesn't work, just moving the screen for a couple frames and snapping back, as if it's trying but failing to un-fullscreen.

Logs: [latest.log](https://github.com/user-attachments/files/17451361/latest.log)
Example Video: [catbox link](https://files.catbox.moe/w94soz.mp4) (because it's too large of a video for github)

The video shows me trying to un-fullscreen, and then also it shows a way that I figured out how to fix it. You have to do this fix upon every game launch.

**Comment by DeeChael** [comment]
yes i noticed this problem and im finding way to fix it

**Comment by DeeChael** [comment]
ok, this problem only appear in two situations:
- start the game with fullscreen mode
- start the game in windowed mode, dont change the window size, get into fullscreen

**Comment by DeeChael** [comment]
fixed in 2.3.0
