### ISSUE TITLE
Doesn't work properly on Fedora 40

### ISSUE THREAD

**Issue by nmackowiakk** [DeeChael/Concentration#39]
![image](https://github.com/user-attachments/assets/96497b84-cfb2-4e31-aa48-2d9fadd4943f)

It basically doesn't hide the top bar in the borderless mode. 
OS: Fedora 40
Mc Version: 1.21.1
Mod Version: 2.3.0

**Comment by DeeChael** [comment]
try EXCLUSIVE?

**Comment by nmackowiakk** [comment]
> try EXCLUSIVE?

The problem is that when I use exclusive mode, my minecraft goes to the last row of alt+tab manager which it would with being in the fullscreen mode. And the alt+tab problem is the reason i'm using the borderless mod.

**Comment by DeeChael** [comment]
as im not using any Linux distro, i have no idea why this happened. one of the reason might be that GLFW thinks the top bar is out of the monitor

**Comment by nmackowiakk** [comment]
For some reason its working now which is great so i'm closing the issue
