### ISSUE TITLE
[Feature Request] Customizable window size?

### ISSUE THREAD

**Issue by Longie520** [DeeChael/Concentration#6]
Would it be possible to add a customizable window size for the borderless window?

Something similar to [Borderless Mining](https://modrinth.com/mod/borderless-mining/versions) which is only maintained up to 1.20.2 at the moment.

If not that's fine - especially that I play on a MacBook and doesn't have the best compat.

**Comment by DeeChael** [comment]
oh, actually I want some feedback from non-windows users, is there any problems using on macos. And I wonder it there any difference between windows and macos because I think changing the window size under borderless fullscreen mode has no different with using windowed mode.

**Comment by Longie520** [comment]
It works fine on MacOS, **except** that the top menu bar and the Dock (equivalent to menu bar) interferes with the borderless fullscreen

<img width="1512" alt="Screenshot 2024-06-18 at 17 40 55" src="https://github.com/DeeChael/Concentration/assets/117007831/f44b8597-2bfd-42c8-bd6b-7173ae9658ad">


The reason that I want borderless small window is solely preference - I just don't like the action bar at the top

<img width="1512" alt="Screenshot 2024-06-18 at 17 43 59" src="https://github.com/DeeChael/Concentration/assets/117007831/82e32e68-cbc1-4efb-9439-0e64424915b9">

**Comment by DeeChael** [comment]
Ok I'll consider it because I don't know where should put the option

**Comment by Longie520** [comment]
> Ok I'll consider it because I don't know where should put the option

Suggestions:

Possibly Mod Menu (as Borderless Mining did)

But I also saw you removing the config screen from Mod Menu from earlier versions... So a separate config screen (that needs a keybind to trigger) can also be good.

**Comment by DeeChael** [comment]
> > Ok I'll consider it because I don't know where should put the option
> 
> Suggestions:
> 
> Possibly Mod Menu (as Borderless Mining did)
> 
> But I also saw you removing the config screen from Mod Menu from earlier versions... So a separate config screen (that needs a keybind to trigger) can also be good.

actually I wanna put it in the video option page just like a vanilla option but I am not sure whether the resolution should use slider to customize or just provide a set of scaled resolution

**Comment by Longie520** [comment]
> actually I wanna put it in the video option page just like a vanilla option but I am not sure whether the resolution should use slider to customize or just provide a set of scaled resolution

i liked the settings page [here](https://modrinth.com/mod/concentration/gallery)

maybe add options like this? for example this is borderless mining's settings in 1.20.1 (and what it looks like on my desktop)
<img width="1512" alt="Screenshot 2024-06-19 at 20 41 57" src="https://github.com/DeeChael/Concentration/assets/117007831/b3d87509-433c-4009-998a-ead4cc5594e4">



edit: at this point i feel like im just asking for borderless mining to update to 1.21 XD
but the dev seems to no longer be maintaining that mod ._.

**Comment by DeeChael** [comment]
> > actually I wanna put it in the video option page just like a vanilla option but I am not sure whether the resolution should use slider to customize or just provide a set of scaled resolution
> 
> i liked the settings page [here](https://modrinth.com/mod/concentration/gallery)
> 
> maybe add options like this? for example this is borderless mining's settings in 1.20.1 (and what it looks like on my desktop) <img alt="Screenshot 2024-06-19 at 20 41 57" width="1512" src="https://private-user-images.githubusercontent.com/117007831/341046065-b3d87509-433c-4009-998a-ead4cc5594e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTY1NzcsIm5iZiI6MTcxODc5NjI3NywicGF0aCI6Ii8xMTcwMDc4MzEvMzQxMDQ2MDY1LWIzZDg3NTA5LTQzM2MtNDAwOS05OThhLWVhZDRjYzU1OTRlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMTI0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzBiOGQ0NGZkYTMxZTQzMzU5NGVlM2JkZjkwZWVhYTNiZWMwODg1NTk0OWIwMjlkYmExOWVhZGY4YzFhZDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LQNXWAmyPpO5LCgvKrUCCs3eaFEXmFK1C9Jpgf5pbzA">
> 
> edit: at this point i feel like im just asking for borderless mining to update to 1.21 XD but the dev seems to no longer be maintaining that mod ._.

Actually one of the reason making me still in consideration is the title bar.
Because when I try to remove the title bar in the borderless fullscreen mode, it turned to be native fullscreen, so I fixed it in a dirty way: manually increase the window height by 1 pixel. It won't affect the gaming experience and can fix the problem.
But when player can customize the window size maybe this problem will appear again. That's why I'm a little bit concerned.

I'm not saying that your suggestion is bad but I think it should be an advanced option so maybe I'll make an extra mod to make some options of the mod customizable

**Comment by Longie520** [comment]
It would be great if you can create a 1.21 fork of Borderless Mining
(I can't code at all so all I can do is ask good devs :D)

**Comment by DeeChael** [comment]
![image](https://github.com/DeeChael/Concentration/assets/63186003/b765ad9e-1fcf-4ea7-8db1-e5ccb0a0819c)
Good news: I implemented customization options
Bad news: the interaction with the game is massed up, actual position and clickable position of the button is totally not same, so I need more time to fix it

**Comment by DeeChael** [comment]
Okay I fixed it.
I'll release this in 1.0.7
But unluckily, to use the config screen you have to install mod menu and this config is for fabric only. Neoforge configuration will be added in 1.0.8.
Thanks for your support.
Have fun!

**Comment by DeeChael** [comment]
1.0.8 with neoforge support released

**Comment by Longie520** [comment]
You are a legend. Thank you and good job!
