### ISSUE TITLE
Vulkan Mod support

### ISSUE THREAD

**Issue by Zorklis** [DeeChael/Concentration#7]
Currently crashing.

**Comment by DeeChael** [comment]
I checked Vulkan Mod source code, it supports Borderless Fullscreen natively, you can turn it on in config.
![image](https://github.com/DeeChael/Concentration/assets/63186003/6e36d1ac-5b94-410c-b3ac-35abd677fc14)

**Comment by Zorklis** [comment]
@DeeChael Yep it does have that option in the menu, except it doesn't work like borderless?
My main faults with it, is that it flashes black screen just like Fullscreen mode does?
And I think my main desire for borderless is so that I can use picture in picture on YouTube videos, which that doesn't show, yet Concentration mod does allow that.

Just my two cents

**Comment by DeeChael** [comment]
> @DeeChael Yep it does have that option in the menu, except it doesn't work like borderless? My main faults with it, is that it flashes black screen just like Fullscreen mode does? And I think my main desire for borderless is so that I can use picture in picture on YouTube videos, which that doesn't show, yet Concentration mod does allow that.
> 
> Just my two cents

Okay I'll check how to fix it up

**Comment by DeeChael** [comment]
> @DeeChael Yep it does have that option in the menu, except it doesn't work like borderless? My main faults with it, is that it flashes black screen just like Fullscreen mode does? And I think my main desire for borderless is so that I can use picture in picture on YouTube videos, which that doesn't show, yet Concentration mod does allow that.
> 
> Just my two cents

Sorry but as Vulkan injected the Window class so I tried many ways to make the borderless fullscreen available but they didn't work. I think the only way is to modify the Vulkan Mod instead of patching Vulkan in Concentration

**Comment by DeeChael** [comment]
compat available in 1.0.9, closed

**Comment by Zorklis** [comment]
Tested, works as it should :)
