### ISSUE TITLE
FO dev would like a toggle

### ISSUE THREAD

**Issue by crg-mad** [DeeChael/Concentration#9]
The developer of the modpack "fabulously optimized" wants a toggle in the game, preferably by just toggling through the different fullscreen options here in the image instead of toggling fullscreen on and off. if this happens it will likely get added to the modpack which i honestly really want to happen as this is the best borderless fullscreen mod out there.

![image](https://github.com/DeeChael/Concentration/assets/141097656/22268654-8195-43e4-b941-e4e19f58b342)

**Comment by DeeChael** [comment]
Well, list in plan, will release in 12 hours

**Comment by crg-mad** [comment]
okay perfect thank you so much, i will forward this to robotkoer

**Comment by DeeChael** [comment]
Okay, tested, works fine. I'll release 1.1.1 later.

Vanilla;
![Vanilla](https://github.com/DeeChael/Concentration/assets/63186003/a6bdfd9c-4ae8-4a42-965a-2c42afae4db2)
with Sodium:
![with Sodium](https://github.com/DeeChael/Concentration/assets/63186003/7cb3384e-eba3-4b5b-8827-8a6d3068e07e)
with Vulkan Mod:
![with Vulkan Mod](https://github.com/DeeChael/Concentration/assets/63186003/82b2770e-619d-497b-b056-42250381d13e)
with Embeddium:
![with Embeddium](https://github.com/DeeChael/Concentration/assets/63186003/8162132d-7f1a-4afb-b160-b2586babaa80)

**Comment by crg-mad** [comment]
amazing work
